<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example</groupId>
  <artifactId>AutoTest-Basic</artifactId>
  <version>1.0.0</version>

  <properties>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <selenium.version>4.39.0</selenium.version>
    <testng.version>7.11.0</testng.version>
    <allure.version>2.29.0</allure.version>
    <allure-maven.version>2.12.0</allure-maven.version>
    <allure.testng.version>2.29.0</allure.testng.version>
    <slf4j.version>2.0.12</slf4j.version>
    <logback.version>1.5.6</logback.version>
    <jackson.version>2.17.1</jackson.version>
    <commons.csv.version>1.10.0</commons.csv.version>
    <surefire.version>3.2.5</surefire.version>
    <suiteXmlFile>src/test/resources/testng-parallel.xml</suiteXmlFile>
    <threads>3</threads>
    <browser>chrome</browser>
    <headless>false</headless>
    <baseUrl>https://www.saucedemo.com</baseUrl>
    <testRetryCount>3</testRetryCount>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-java</artifactId>
      <version>${selenium.version}</version>
    </dependency>

    <dependency>
      <groupId>org.testng</groupId>
      <artifactId>testng</artifactId>
      <version>${testng.version}</version>
<!--      <scope>test</scope>-->
    </dependency>

    <dependency>
      <groupId>io.qameta.allure</groupId>
      <artifactId>allure-testng</artifactId>
      <version>${allure.testng.version}</version>
    </dependency>

    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>${slf4j.version}</version>
    </dependency>
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <version>${logback.version}</version>
    </dependency>

    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-csv</artifactId>
      <version>${commons.csv.version}</version>
    </dependency>

    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>${jackson.version}</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.11.0</version>
        <configuration>
          <release>17</release>
        </configuration>
      </plugin>
      <plugin>
        <groupId>io.qameta.allure</groupId>
        <artifactId>allure-maven</artifactId>
        <version>${allure-maven.version}</version>
        <configuration>
          <reportVersion>${allure.version}</reportVersion>
          <resultsDirectory>${project.basedir}/allure-results</resultsDirectory>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${surefire.version}</version>
        <configuration>
          <suiteXmlFiles>
            <suiteXmlFile>${suiteXmlFile}</suiteXmlFile>
          </suiteXmlFiles>
          <systemPropertyVariables>
            <threads>${threads}</threads>
            <browser>${browser}</browser>
            <headless>${headless}</headless>
            <baseUrl>${baseUrl}</baseUrl>
            <testRetryCount>${testRetryCount}</testRetryCount>
          </systemPropertyVariables>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>