baseUrl=https://www.saucedemo.com
defaultBrowser=chrome
headless=false
implicitWaitSec=0
explicitWaitSec=10
pageLoadTimeoutSec=30
screenshotOnFail=true
retryCount=1
grid.enabled=false
grid.url=http://localhost:4444/wd/hub